connected redux to the application, created components: HeaderPage, MainPage, rendered when there are posts and when there are none, also created a component (ErrorMessage) that renders an error
VsevolodEpihin/epihin_site_post_frontend pull request #1
Opened 2024-06-11 10:50 UTC by VsevolodEpihin

connected redux to the application, created components: HeaderPage, MainPage, rendered when there are posts and when there are none, also created a component (ErrorMessage) that renders an error

![Снимок экрана от 2024-06-11 12-59-40](https://github.com/VsevolodEpihin/epihin_site_post_frontend/assets/164314233/6d845162-d879-47a7-8b67-ec32160bdf9b)
![Снимок экрана от 2024-06-11 13-45-37](https://github.com/VsevolodEpihin/epihin_site_post_frontend/assets/164314233/d90cd851-2f13-4882-856f-b7a7a1395dc8)
![Снимок экрана от 2024-06-11 13-02-54](https://github.com/VsevolodEpihin/epihin_site_post_frontend/assets/164314233/bcae4400-7868-436a-b83b-dcee0aba4868)

2024-06-11 11:35 UTC, ekaterinagaltsova commented on package.json
> +    "@reduxjs/toolkit": "^2.2.5",
тулкит зачем?)

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/App.tsx
> +import './normalize.css';
не стоит

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/App.tsx
> +      <HeaderPage />
Header - это не страница - это просто компонент

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/App.tsx
> +      <MainPage />
а это страница - и должна храниться в папке src/pages/MainPage

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/components/ErrorMessage/ErrorMessage.module.css
> +.containerError{
+s

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/components/ErrorMessage/ErrorMessage.tsx
> +const ErrorMessage: React.FC<ErrorMessageProps> = ({ error }) => {
const ErrorMessage = ({ error }: ErrorMessageProps) => {

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/App.tsx
>  function App() {
а все остальные - стрелочные

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/components/ErrorMessage/ErrorMessage.tsx
> +  console.log(error);
пупупу(

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/components/ErrorMessage/ErrorMessage.tsx
> +      {error ?
явные проверки!
но сам блок не логичен
по названию - только для ошибки
если он универсальный - надо поменять нейминг и прокидывать сам текст сообщения

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/components/HeaderPage/HeaderPage.module.css
> +color: blueviolet;
+2s

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/components/HeaderPage/HeaderPage.tsx
> +import logo from '../../image/logo.png';
почитай типовые в части порядка импорта

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/components/HeaderPage/HeaderPage.tsx
> +          {<img
зачем фигурные?

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/components/HeaderPage/HeaderPage.tsx
> +          <a href="##">Create Profile</a>
не стоит пока оборачивать в тег а

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/components/Loader/Loader.tsx
> +const Loader: React.FC<LoaderProps> = ({ isLoading }) => {
top

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/components/Loader/Loader.tsx
> +const Loader: React.FC<LoaderProps> = ({ isLoading }) => {
этот компонент вызывается только когда  isLoading - зачем он тут пропсом?

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/components/Loader/Loader.tsx
> +
-/n

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/components/Loader/Loader.tsx
> +          {
лучше все, что объявляется так в return компонентов выносить туда где оно не будет пересоздаваться каждый раз

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/components/Loader/Loader.tsx
> +        <ClipLoader
может уже все из материал взять?

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/components/MainPage/MainPage.tsx
> +import { useDispatch, useSelector } from 'react-redux';
эти хуки надо типизировать
https://redux.js.org/usage/usage-with-typescript#typing-additional-redux-logic

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/components/MainPage/MainPage.tsx
> +import PostList from '../PostList/PostList';
импорт(

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/components/MainPage/MainPage.tsx
> +const MainPage: React.FC = () => {
не стооит типизировать - подтянется само

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/components/MainPage/MainPage.tsx
> +    axios.get<Posts[]>('http://localhost:3000/posts/')
когда подключен стейт-менеджер - вся логика запросов переноситься туда

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/components/MainPage/MainPage.tsx
> +    axios.get<Posts[]>('http://localhost:3000/posts/')
путь к беку - в енв

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/components/MainPage/MainPage.tsx
> +        dispatch(fetchPostsSuccess(response.data));
это все должно быть в саге

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/components/MainPage/MainPage.tsx
> +      <Loader isLoading={isLoading} />
{isLoading &&  <Loader  />}
условный рендеринг

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/components/MainPage/MainPage.tsx
> +      {error || !posts.length ? <ErrorMessage error={error} /> : <PostList posts={posts} />}
логика вывода ошибки и отображения новостей - разные)

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/components/PostList/PostList.tsx
> +  return(<>
+/n

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/components/PostList/PostList.tsx
> +        <div
код отрисовки одного таска унеси в отдельный компонент

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/components/PostList/PostList.tsx
> +              src={post.imageUrl}
одного хватит)

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/components/PostList/PostList.tsx
> +              {post.tags.map(tag => (
тоже лучше унести в отдельный компоент

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/redux/actions/actionPosts.ts
> +export const fetchPostsFail = (error: null | string) => {
только стринг -

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/redux/reducers/postReducer.ts
> +import { FETCH_POSTS_REQUEST, FETCH_POSTS_FAIL, FETCH_POSTS_SUCCESS } from '../actions/actionPosts';
константы тянуть из экшенов странновато)

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/redux/reducers/postReducer.ts
> +  loading: false,
все булевое начинается с is/has

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/redux/reducers/rootReducer.ts
> +import postReducer from './postReducer';
bvgjhn(

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/redux/sagas/postSaga.ts
> +  return response.data;
перемести эту функцию в redux/api/postsApi

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/redux/sagas/postSaga.ts
> +  } catch (error) {
catch (error: unknown)

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/redux/sagas/postSaga.ts
> +      yield put(fetchPostsFail(error.message));
const currentError = error instanceof Error) 
? error.message
:  DEFAULT_ERROR:
      yield put(fetchPostsFail(currentError);
    }

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/redux/store.ts
> +import { configureStore } from '@reduxjs/toolkit';
вот где подвох) не надо лишней бибки..

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/types/index.ts
> +  imageUrl?:string | null
зачем опционально?

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/types/index.ts
> +export interface Tags{
+s

2024-06-11 11:35 UTC, ekaterinagaltsova commented on src/types/index.ts
> +export interface PostsListProps{
выглядит как интерфейс пропсов компонента  - такое хранят в компоненте

2024-06-17 07:28 UTC, ekaterinagaltsova commented on .env.example
> +VITE_API_URL=http://127.0.0.1:3006
VITE_API_URL='http://127.0.0.1:3006'
+\n

2024-06-17 07:28 UTC, ekaterinagaltsova commented on package.json
> +    "dotenv": "^16.4.5",
unistall

2024-06-17 07:28 UTC, ekaterinagaltsova commented on src/components/ErrorMessage/ErrorMessage.tsx
> +  error: string | null ;
думаю - не стоит вызывать этот компонент - если error - null

2024-06-17 07:28 UTC, ekaterinagaltsova commented on src/components/Loader/Loader.tsx
> +      <Box
в одну строку

2024-06-17 07:28 UTC, ekaterinagaltsova commented on src/components/PostItem/PostItem.tsx
> +const Post = ({ imageUrl, title, text, user, tags }: PostsListProps) => {
PostsListProps
название интерфейса пропсов - имя компонета + Props = PostProps

2024-06-17 07:28 UTC, ekaterinagaltsova commented on src/components/PostItem/PostItem.tsx
> +const Post = ({ imageUrl, title, text, user, tags }: PostsListProps) => {
больше трех - в столбик)

2024-06-17 07:28 UTC, ekaterinagaltsova commented on src/components/PostItem/PostItem.tsx
> +            {tags.map(tag => (
не логично) лучше компонет Tags -  который примет массив и отрисует - уменьшит код здесь

2024-06-17 12:39 UTC, ekaterinagaltsova commented on src/components/Header/Header.module.css
> +span :hover {
-s

2024-06-17 12:39 UTC, ekaterinagaltsova commented on src/components/PostList/PostList.tsx
> +        {posts.map(post => (
posts.length > 0 &&

2024-06-17 12:39 UTC, ekaterinagaltsova commented on src/components/Tags/Tags.tsx
> +import { Tag } from "../../types";
pupupu

2024-06-17 12:39 UTC, ekaterinagaltsova commented on src/components/Tags/Tags.tsx
> +        >{tag.text}</span>
+/n
+/n

2024-06-17 12:39 UTC, ekaterinagaltsova commented on src/errorMessage.ts
> +export const errorMessage = "Posts were not loaded";
single

2024-06-17 12:39 UTC, ekaterinagaltsova commented on src/redux/api/api.ts
> +import axios from "axios";
single

2024-06-17 12:39 UTC, ekaterinagaltsova commented on src/redux/reducers/postReducer.ts
> +} from "../actionTypes";
(

2024-06-17 12:39 UTC, ekaterinagaltsova commented on src/redux/reducers/postReducer.ts
> +          ?
? action.payload
 :   initialState.posts,

2024-06-17 13:56 UTC, s-skubedin requested changes

2024-06-17 13:56 UTC, s-skubedin commented on src/App.tsx
> +import Header from './components/Header/Header';
Используй index файлы для re-export

2024-06-17 13:56 UTC, s-skubedin commented on src/components/ErrorMessage/ErrorMessage.tsx
> +    <>
Фрагмент избыточен

2024-06-17 13:56 UTC, s-skubedin commented on src/components/Header/Header.tsx
> +            src={logo}
Используй pubic path вместо import

2024-06-17 13:56 UTC, s-skubedin commented on src/components/PostItem/PostItem.module.css
> +  height: 12%;
Странные значения. На мобильных устройствах и широких экранах может работать не пердсказуемо.

Используй кратные значения, 25% / 33% / 50% (четверть, треть, половина) или px, em, rem

2024-06-17 13:56 UTC, s-skubedin commented on src/components/PostList/PostList.tsx
> +        {posts.length === 0 &&  <PostNotFound />}
Лишний пробел

2024-06-17 13:56 UTC, s-skubedin commented on src/redux/store.ts
> +sagaMiddleware.run( rootSaga );
Лишний пробел

2024-06-17 13:56 UTC, s-skubedin commented on src/types/index.ts
> +export interface Posts{
Отсутствует пробел

2024-06-18 07:39 UTC, s-skubedin requested changes

2024-06-18 07:39 UTC, s-skubedin commented on src/pages/MainPage.tsx
> +import Loader from '../components/Loader/Loader';
Используй index файл для re-export

2024-06-18 07:39 UTC, s-skubedin commented on src/components/PostItem/PostItem.tsx
> +import notImage from '../../image/no-photo.png';
Используй public директорию

2024-06-18 09:57 UTC, merged